# Generated by Django 3.1.1 on 2022-04-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
