# Generated by Django 3.1.1 on 2023-04-28 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_auto_20230428_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.IntegerField(choices=[(1, 'Спорт талимга кабул'), (2, 'Спорт унвонлари ва разрядлари'), (3, 'Спорт паспортини бериш')], default=0)),
                ('grade_type', models.IntegerField(choices=[(5, 'Perfect'), (4, 'Good'), (3, 'Unsatisfactory')], default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.district')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.staff')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.organization')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.region')),
            ],
            options={
                'db_table': 'employee_rating',
            },
        ),
    ]
