# Generated by Django 3.1.1 on 2023-04-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_employeerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerating',
            name='service_type',
            field=models.IntegerField(choices=[(1, "Sport ta'lim muassasalarini qabul qilish"), (2, 'Sport unvonlari va sport razryadlarini berish'), (3, 'Sportchi passporti berish')], default=0),
        ),
    ]
