# Generated by Django 3.1.1 on 2023-06-07 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0011_auto_20230606_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.organization'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='education',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='experience',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='middlename',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='phone',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='place_of_birth',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='position',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
