# Generated by Django 4.1.3 on 2023-08-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_auto_20230612_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministrystructure',
            name='image',
            field=models.ImageField(null=True, upload_to='structure'),
        ),
    ]
