# Generated by Django 4.1.3 on 2023-08-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_ministrystructure_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static_page'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static_page'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='main_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
