# Generated by Django 4.1.3 on 2023-08-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_staticpage_icon_staticpage_image_staticpage_main_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500, null=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static_data')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static_data')),
                ('file', models.FileField(blank=True, null=True, upload_to='static_data')),
                ('main_url', models.CharField(max_length=500, null=True)),
                ('views', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'static_datas',
                'ordering': ['-id'],
            },
        ),
    ]
