# Generated by Django 4.1.3 on 2023-08-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_staticdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticdata',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staticdata',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staticdata',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staticdata',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='staticdata',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='staticdata',
            name='title_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
