# Generated by Django 4.1.3 on 2023-08-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_staticdata_content_en_staticdata_content_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticdata',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='title_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='title_uz',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
