# Generated by Django 3.1.1 on 2023-08-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_auto_20230811_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='browser',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
