# Generated by Django 3.1.1 on 2023-09-18 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_auto_20230814_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderNotices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('built_year', models.IntegerField(blank=True, default=0, null=True)),
                ('land_area', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('number', models.IntegerField(blank=True, default=0)),
                ('organizer', models.CharField(blank=True, max_length=500, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.region')),
            ],
            options={
                'db_table': 'tender_notices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderNoticesPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tender_notices')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.tendernotices')),
            ],
            options={
                'db_table': 'tender_notices_photos',
                'ordering': ['-id'],
            },
        ),
    ]
