# Generated by Django 3.1.1 on 2023-09-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_auto_20230918_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendernotices',
            name='organizer',
        ),
    ]
