# Generated by Django 3.1.1 on 2023-09-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_remove_tendernotices_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendernotices',
            name='organizer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
