# Generated by Django 3.1.1 on 2023-10-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_contact_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('title_uz', models.CharField(max_length=500, null=True)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('title_ru', models.CharField(max_length=500, null=True)),
                ('title_sr', models.CharField(max_length=500, null=True)),
                ('content', models.TextField()),
                ('content_uz', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_ru', models.TextField(null=True)),
                ('content_sr', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'car_info',
            },
        ),
        migrations.CreateModel(
            name='CarTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_uz', models.CharField(max_length=500, null=True)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('title_ru', models.CharField(max_length=500, null=True)),
                ('title_sr', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'car_types',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('model_uz', models.CharField(max_length=100, null=True)),
                ('model_en', models.CharField(max_length=100, null=True)),
                ('model_ru', models.CharField(max_length=100, null=True)),
                ('model_sr', models.CharField(max_length=100, null=True)),
                ('number', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('comment_uz', models.TextField(blank=True, null=True)),
                ('comment_en', models.TextField(blank=True, null=True)),
                ('comment_ru', models.TextField(blank=True, null=True)),
                ('comment_sr', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.cartypes')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.staff')),
            ],
            options={
                'db_table': 'cars',
                'ordering': ['-created_at'],
            },
        ),
    ]
