# Generated by Django 3.1.1 on 2023-10-26 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_institutionitem_institutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionitem',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.institutions'),
        ),
    ]
