# Generated by Django 3.1.1 on 2023-10-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_auto_20231026_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institutions',
            new_name='OrganizationType',
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.organizationtype'),
        ),
        migrations.AlterModelTable(
            name='organizationtype',
            table='organization_type',
        ),
        migrations.DeleteModel(
            name='InstitutionItem',
        ),
    ]
